# Generated by Django 5.2.7 on 2025-10-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_rename_tmp_id_book_id"),
        ("meetings", "0003_alter_meeting_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meeting",
                to="books.book",
            ),
            preserve_default=False,
        ),
    ]
