# Generated by Django 5.2.7 on 2025-10-08 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_meeting_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="id",
        ),
        migrations.AddField(
            model_name="meeting",
            name="tmp_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
