# Generated by Django 5.2.7 on 2025-10-08 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_remove_meeting_id_meeting_tmp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="tmp_id",
            new_name="id",
        ),
    ]
