# Generated by Django 5.2.7 on 2025-10-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0006_rename_tmp_id_meeting_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("PAST", "Past"), ("FUTURE", "Future")],
                default="FUTURE",
                max_length=16,
            ),
        ),
    ]
