# Generated by Django 5.2.7 on 2025-10-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_remove_book_id_book_tmp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="tmp_id",
            new_name="id",
        ),
    ]
