# Generated by Django 5.2.6 on 2025-09-29 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrumpySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton_id",
                    models.IntegerField(
                        default=1,
                        editable=False,
                        help_text="An ID to use for this mixin, in case the model uses some non-standard PK.",
                    ),
                ),
                (
                    "allow_signin",
                    models.BooleanField(
                        default=True, help_text="Allow users to signin."
                    ),
                ),
                (
                    "allow_signup",
                    models.BooleanField(
                        default=True, help_text="Allow users to register."
                    ),
                ),
                (
                    "require_verification",
                    models.BooleanField(
                        default=True,
                        help_text="Require a user to be manually verified.",
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=6, help_text="Minimum length of a user password"
                    ),
                ),
                (
                    "password_max_length",
                    models.PositiveIntegerField(
                        default=255, help_text="Maximum length of a user password"
                    ),
                ),
                (
                    "password_strength",
                    models.IntegerField(
                        default=2,
                        help_text="Strength of password field as per <a href='github.com/dropbox/zxcvbn'>zxcvbn</a>",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "max_free_books",
                    models.PositiveIntegerField(
                        default=2, help_text="Number of unread books a user can own."
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
    ]
