# Generated by Django 5.2.7 on 2025-10-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grumpysettings",
            name="require_verification",
        ),
        migrations.AddField(
            model_name="grumpysettings",
            name="require_approval",
            field=models.BooleanField(
                default=False, help_text="Require a user to be manually approved."
            ),
        ),
    ]
