# Generated by Django 5.2.7 on 2025-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_grumpysettings_require_verification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grumpysettings",
            name="notify_signups",
            field=models.BooleanField(
                default=False, help_text="Notify managers when a new user signs up."
            ),
        ),
    ]
