# Generated by Django 5.2.6 on 2025-10-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
    ]
