# Generated by Django 5.2.6 on 2025-09-29 21:11

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of site.", null=True
                    ),
                ),
                (
                    "show_admin_notice",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not to show a site-specific notice in the Admin.",
                    ),
                ),
                (
                    "admin_notice_color",
                    colorfield.fields.ColorField(
                        default="#CCCCCC",
                        help_text="Color of site-specific notice in the Admin.",
                        image_field=None,
                        max_length=25,
                        samples=[
                            ("#CCCCCC", "Grey"),
                            ("#009933", "Green"),
                            ("#FFAA00", "Yellow"),
                            ("#FF0000", "Red"),
                        ],
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        help_text="Associated site.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Profile",
                "verbose_name_plural": "Site Profiles",
            },
        ),
    ]
